kubesphere/test-infra

OWNERS, config/jobs/kubesphere/test-infra/test-infra-postsubmits.yaml, config/prow/cluster/crier_deployment.yaml, config/prow/cluster/tide_deployment.yaml, config/prow/config.yaml
Add missing s3 config to crier and update OWNERS file
=> Add missing s3 credentials

config/prow/plugins.yaml
ref: https://github.com/kubernetes/test-infra/pull/22663
=> Retain LGTM through squashes

config/jobs/kubesphere/kubesphere/kubesphere-postsubmits.yaml
Fix kubesphere periodicly image building job
/kind flake
=> fix kubesphere operiodicly image building

config/prow/plugins.yaml
According to https://github.com/kubernetes/test-infra/blob/master/config/prow/plugins.yaml#L376, add maintainers team configuration.
=> add milestone maintainer team

images/build-tools/Dockerfile
Add kubebuilder bin directory to PATH so we could use kubectl
=> add kubebuilder bin directory to PATH

config/prow/plugins.yaml
channel `test-and-release` doesn't exist, change it to `prow`
=> update slack reporter channel

config/prow/README.md
=> update test readme

config/jobs/kubesphere/console/console-presubmits.yaml
1. `yarn && yarn test` to run the tests
2. `yarn && yarn build` to build 
=> add console presubmit job

config/jobs/kubesphere/console/console-postsubmits.yaml
Fixes #16 
1. Add a postsubmits job that builds images and push images
2. Add a daily build job.
=> Add console postsubmits job

config/jobs/kubesphere/kubesphere/kubesphere-postsubmits.yaml, config/prow/config.yaml
Docker load credentials at default location `$HOME/.docker/config.json`
=> fix docker credential mount location

config/jobs/kubesphere/console/console-postsubmits.yaml, config/jobs/kubesphere/console/console-presubmits.yaml
=> add branch validation for console job

config/prow/plugins.yaml
=> Add milestone plugins for kubesphere/ks-devops repo

config/jobs/kubesphere/test-infra/test-infra-postsubmits.yaml, config/prow/Makefile, config/prow/labels.yaml
Add label sync job, it runs every hour
```yaml
- cron: "17 * * * *"  # Every hour at 17 minutes past the hour
```
=> add label sync job

config/prow/labels.yaml
Signed-off-by: Patrick-LuoYu <patrickluo@yunify.com>
=> Add label require-ui-text-review.

config/prow/labels.yaml
Signed-off-by: Patrick-LuoYu <patrickluo@yunify.com>
/assign @zryfish
=> Change description of label require-ui-text-review to fix a problem.

config/jobs/kubesphere/kubesphere/kubesphere-postsubmits.yaml, config/jobs/kubesphere/kubesphere/kubesphere-presubmits.yaml
=> add e2e test

config/jobs/kubesphere/console/console-postsubmits.yaml, config/jobs/kubesphere/console/console-presubmits.yaml
Using development repo instead of production repo for build console images.
=> change console build image repo to dev

config/prow/config.yaml, config/prow/plugins.yaml
Signed-off-by: Zhengyi Lai <zheng1@kubesphere.io>
=> Add the config of openelb

config/jobs/kubesphere/test-infra/test-infra-postsubmits.yaml, config/prow/config.yaml
Signed-off-by: Zhengyi Lai <zheng1@kubesphere.io>
=> Add tide & label-sync to openelb

config/jobs/kubesphere/console/console-postsubmits.yaml
Change console build job default requests to 4c4g
=> Change console build default requests

images/build-tools/Dockerfile, images/build-tools/build-and-push.sh
Related to https://github.com/kubesphere/kubesphere/pull/5045, failed to pass pull-kubesphere-unit-test.
=> Upgrade go version to v1.18.4

config/jobs/kubesphere/kubesphere/kubesphere-postsubmits.yaml
Update default docker image repo to `kubespheredev`
=> Update default docker image repo

images/build-tools/Dockerfile, images/build-tools/build-and-push.sh
ref: https://github.com/kubesphere/kse/pull/878
/cc @wansir
=> Bump go version to 1.20

config/jobs/kubesphere/kubesphere/kubesphere-postsubmits.yaml, config/jobs/kubesphere/kubesphere/kubesphere-presubmits.yaml, images/build-tools/Dockerfile, images/build-tools/build-and-push.sh
https://github.com/kubesphere/project/issues/3709#issuecomment-2147057312
fix:
test result:
=> feat: build new image.

config/jobs/kubesphere/console/console-presubmits.yaml
base: https://github.com/kubesphere/console/pull/4276
fixed:
=> feat: change console test image tag.

config/jobs/kubesphere/console/console-presubmits.yaml
delete pull-console-unit-test.
base: https://github.com/kubesphere/console/pull/4276
=> feat: delete pull-console-unit-test.

config/jobs/kubesphere/console/console-postsubmits.yaml, config/jobs/kubesphere/kubesphere/kubesphere-postsubmits.yaml, config/prow/config.yaml
=> feat: use action replace prow to build image.
